

-- Table Definitions

-- (User) 유저
CREATE SCHEMA IF NOT EXISTS user_write;
CREATE SCHEMA IF NOT EXISTS user_read;

CREATE TABLE IF NOT EXISTS user_write.user_user (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255),
    picture VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_read.user_user (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255),
    picture VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);
COMMENT ON TABLE user_write.user_user IS '사용자 마스터 정보 (Read/Write 출처)';

CREATE SCHEMA IF NOT EXISTS auth_write;

CREATE TABLE IF NOT EXISTS auth_write.auth_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(255) NOT NULL,
    provider_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_user_provider_provider_id UNIQUE (provider, provider_id)
);
COMMENT ON TABLE auth_write.auth_user IS '소셜 인증 정보';

CREATE TABLE IF NOT EXISTS auth_write.outbox (
    id UUID PRIMARY KEY,
    aggregate_type VARCHAR(255) NOT NULL,
    aggregate_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    payload TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL
);
COMMENT ON TABLE auth_write.outbox IS '이벤트 발행 아웃박스';

-- 그룹 (CQRS)

CREATE SCHEMA IF NOT EXISTS group_write;
CREATE SCHEMA IF NOT EXISTS group_read;

-- Write-side tables
CREATE TABLE IF NOT EXISTS group_write.group_group (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255),
    invite_code VARCHAR(255) UNIQUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

COMMENT ON TABLE group_write.group_group IS '그룹 마스터 정보 (Write)';

CREATE TABLE IF NOT EXISTS group_write.group_member (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    user_name VARCHAR(255),
    group_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_group_member_group FOREIGN KEY (group_id)
        REFERENCES group_write.group_group(id),
    CONSTRAINT fk_group_member_user FOREIGN KEY (user_id)
        REFERENCES user_write.user_user(id)
);
COMMENT ON TABLE group_write.group_member IS '그룹 멤버십 (Write)';

-- Read-side tables
CREATE TABLE IF NOT EXISTS group_read.group_group (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255),
    invite_code VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);
COMMENT ON TABLE group_read.group_group IS '그룹 정보 (Read)';



CREATE TABLE IF NOT EXISTS group_read.group_member (

    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    user_name VARCHAR(255),
    group_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_group_member_group FOREIGN KEY (group_id) REFERENCES group_read.group_group(id)
);

COMMENT ON TABLE group_read.group_member IS '그룹 멤버십 (Read)';

-- 일기
CREATE TABLE diary (
    id          BIGSERIAL        PRIMARY KEY,
    group_id    BIGINT           NOT NULL,
    user_id     BIGINT           NOT NULL,
    user_name   VARCHAR(255)     NOT NULL,
    title       VARCHAR(255)     NOT NULL,
    content     TEXT             NOT NULL,
    status      VARCHAR(20)     NOT NULL,
    created_at  TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP        NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_diary_group FOREIGN KEY (group_id) REFERENCES group_write.group_group(id),
    CONSTRAINT fk_diary_user  FOREIGN KEY (user_id)  REFERENCES user_write.user_user(id)
);
COMMENT ON TABLE diary IS '일기 정보';

-- 미디어
CREATE TABLE diary_media (
    id          BIGSERIAL        PRIMARY KEY,
    diary_id    BIGINT           NOT NULL,
    media_type  VARCHAR(20)       NOT NULL,
    file_url    VARCHAR(500)     NOT NULL,
    s3_key      VARCHAR(500)     NOT NULL,
    order_index INT              DEFAULT 0,
    created_at  TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP        NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_diary_media_diary_order UNIQUE (diary_id, order_index),
    CONSTRAINT fk_diary_media_diary FOREIGN KEY (diary_id) REFERENCES diary(id)
);
COMMENT ON TABLE diary_media IS '일기 미디어';

-- 댓글
CREATE TABLE diary_comment (
    id          BIGSERIAL        PRIMARY KEY,
    diary_id    BIGINT           NOT NULL,
    user_id     BIGINT           NOT NULL,
    content     TEXT             NOT NULL,
    status      VARCHAR(20)   NOT NULL,
    created_at  TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP        NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_diary_comment_diary FOREIGN KEY (diary_id) REFERENCES diary(id),
    CONSTRAINT fk_diary_comment_user  FOREIGN KEY (user_id) REFERENCES user_write.user_user(id)
);
COMMENT ON TABLE diary_comment IS '일기 댓글';

-- 감정 분석 레포트
CREATE TABLE report (
    id          BIGSERIAL        PRIMARY KEY,
    user_id     BIGINT           NOT NULL,
    type        VARCHAR(20)      NOT NULL,
    start_date  DATE             NOT NULL,
    end_date    DATE             NOT NULL,
    content     TEXT             NOT NULL,
    created_at  TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_report_user FOREIGN KEY (user_id) REFERENCES user_write.user_user(id)
);
COMMENT ON TABLE report IS '주간/월간 리포트';

-- 감정 분석
CREATE TABLE sentiment_analysis (
    id             BIGSERIAL        PRIMARY KEY,
    diary_id       BIGINT           NOT NULL,
    angry          SMALLINT         NOT NULL DEFAULT 0 CHECK (angry >= 0),
    sad            SMALLINT         NOT NULL DEFAULT 0 CHECK (sad >= 0),
    anxious        SMALLINT         NOT NULL DEFAULT 0 CHECK (anxious >= 0),
    hurt           SMALLINT         NOT NULL DEFAULT 0 CHECK (hurt >= 0),
    embarrass      SMALLINT         NOT NULL DEFAULT 0 CHECK (embarrass >= 0),
    happy          SMALLINT         NOT NULL DEFAULT 0 CHECK (happy >= 0),
    summary        TEXT             NOT NULL,
    source         VARCHAR(32)      NOT NULL DEFAULT 'local',
    confidence     DECIMAL(5,4)     NOT NULL,
    model_version  VARCHAR(64)      NOT NULL DEFAULT 'unknown',
    llm_model      VARCHAR(64)      NOT NULL,
    content_hash   CHAR(64)         NOT NULL,
    analyzed_at    TIMESTAMP        NOT NULL,
    created_at     TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sentiment_analysis_diary FOREIGN KEY (diary_id) REFERENCES diary(id)
);
COMMENT ON TABLE sentiment_analysis IS '일기 감정 분석 결과';

-- 감정 분석 상태
CREATE TABLE sentiment_job (
    id                    BIGSERIAL    PRIMARY KEY,
    diary_id              BIGINT       NOT NULL,
    sentiment_analysis_id BIGINT       NULL,
    content_hash          CHAR(64)     NOT NULL,
    status                VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    retry_count           INT          NOT NULL DEFAULT 0,
    last_error            TEXT         NULL,
    created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sentiment_job_diary    FOREIGN KEY (diary_id) REFERENCES diary(id),
    CONSTRAINT fk_sentiment_job_analysis FOREIGN KEY (sentiment_analysis_id) REFERENCES sentiment_analysis(id)
);
COMMENT ON TABLE sentiment_job IS '감정 분석 작업 관리';

-- 카메라 (새 스키마)
CREATE TABLE camera (
    id            BIGSERIAL        PRIMARY KEY,
    name          VARCHAR(200)     NOT NULL,
    rtsp_url      VARCHAR(1000)    NOT NULL,
    stream_name   VARCHAR(200)     NULL,
    config_json   TEXT             NULL,
    owner_user_id BIGINT           NULL,
    armed         BOOLEAN          NOT NULL DEFAULT TRUE,
    sensitivity   DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    created_at    TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (stream_name)
);
COMMENT ON TABLE camera IS '카메라 정보';
CREATE INDEX idx_camera_name ON camera (name);

-- 이벤트 (새 스키마)
CREATE TABLE event (
    id           BIGSERIAL        PRIMARY KEY,
    camera_id    BIGINT           NOT NULL,
    type         VARCHAR(100)     NOT NULL,
    payload_json TEXT             NULL,
    clip_url     VARCHAR(1000)    NULL,
    occurred_at  TIMESTAMP        NULL,
    created_at   TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_event_camera
        FOREIGN KEY (camera_id)
        REFERENCES camera(id)
        ON DELETE CASCADE
);
COMMENT ON TABLE event IS '이벤트 로그';
CREATE INDEX idx_event_camera_occurred_at ON event (camera_id, occurred_at);

-- 쇼츠 (새 스키마)
CREATE TABLE shorts (
    id              BIGSERIAL        PRIMARY KEY,
    camera_id       BIGINT           NOT NULL,
    source_event_id BIGINT           NULL,
    status          VARCHAR(20)    NOT NULL,
    clip_url        VARCHAR(1000)    NULL,
    thumb_url       VARCHAR(1000)    NULL,
    duration_sec    DECIMAL(10,2)    NULL,
    created_at      TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_shorts_camera
        FOREIGN KEY (camera_id)
        REFERENCES camera(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_shorts_event
        FOREIGN KEY (source_event_id)
        REFERENCES event(id)
        ON DELETE SET NULL
);
COMMENT ON TABLE shorts IS '이벤트 기반 쇼츠 영상';
CREATE INDEX idx_shorts_camera_status_created ON shorts (camera_id, status, created_at);
CREATE INDEX idx_shorts_source_event ON shorts (source_event_id);

-- 첨부파일 (Attachment)
CREATE TABLE attachment (
    id          BIGSERIAL        PRIMARY KEY,
    diary_id    BIGINT           NOT NULL,
    type        VARCHAR(20)       NOT NULL,
    url         VARCHAR(500)     NOT NULL,
    origin_name VARCHAR(255)     NOT NULL,
    CONSTRAINT fk_attachment_diary FOREIGN KEY (diary_id) REFERENCES diary(id) ON DELETE CASCADE
);
COMMENT ON TABLE attachment IS '일기 첨부파일';
